// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7X9lHerKtN6JMa92otQFrw9C62vZluJc',
    appId: '1:20779677637:web:3f73acc88e235535143dac',
    messagingSenderId: '20779677637',
    projectId: 'resqnet-app-f3027',
    authDomain: 'resqnet-app-f3027.firebaseapp.com',
    storageBucket: 'resqnet-app-f3027.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOpS56NzImWASfv5VuK542KQ_IwgtUv8',
    appId: '1:20779677637:android:44d5a750c85f15ca143dac',
    messagingSenderId: '20779677637',
    projectId: 'resqnet-app-f3027',
    storageBucket: 'resqnet-app-f3027.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7X9lHerKtN6JMa92otQFrw9C62vZluJc',
    appId: '1:20779677637:web:b12051970d724086143dac',
    messagingSenderId: '20779677637',
    projectId: 'resqnet-app-f3027',
    authDomain: 'resqnet-app-f3027.firebaseapp.com',
    storageBucket: 'resqnet-app-f3027.firebasestorage.app',
  );

}